### ISSUE TITLE
Invalid date reported for date intervals in eventDate

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/gbif-data-validator#60]
It is reporting invalid dates for ISO8601 date ranges. Example: 1943-01-01/1943-12-31. 

From https://github.com/gbif/portal-feedback/issues/607

**Comment by MattBlissett** [comment]
These aren't yet supported by GBIF's indexing.

**Comment by tucotuco** [comment]
That may be, but that does not make them invalid.

**Comment by MattBlissett** [comment]
The GBIF data validator is intended primarily to help GBIF data publishers, so it reflects the processing and interpretation that GBIF does.

When we support data ranges for occurrence data (https://github.com/gbif/gbif-api/issues/4) then the validator will also support them.

**Comment by tucotuco** [comment]
I get it, but this is the kind of situation where it is important to understand the resulting perceptions of the community, for whom actually work is created to try to be good citizens when in fact they were perfectly correct to begin with. Not good for GBIF, not good for the people who go to the effor to try to figure out what is wrong.

**Comment by cgendreau** [comment]
By default, the validator uses a direct mapping between the current flag of the processing library (`OccurrenceIssue`) and its own flag (`EvaluationType`). It it possible to use a different flag that could say, for example, `..._NOT_INTERPRETABLE` instead of `..._INVALID`. This is not really a solution but it could help in the meantime.

**Comment by MattBlissett** [comment]
The validator is now updated to the same as the GBIF portal, to take the start of the date range.
