### ISSUE TITLE
Questions about the data processing status of GBIF data validator

### ISSUE THREAD

**Issue by kcopas** [gbif/gbif-data-validator#72]
via email to Communications:
 
Hi, I’m Yi-Hsuan Li, the data administrator of TaiBIF.

Last week, I used GBIF data validator to check the quality of our checklist data (The size of the file "Taxon.csv" I uploaded is about 51.3MB). It has been processing for seven days and still processing now, I am wondering if it is reasonable.

The email address I used to register GBIF account is lyh.yihsuan@gmail.com
And the job id are 1521462679720 and 1524126551668

**Comment by ghost** [comment]
@fmendezh @thomasstjerne Any updates to this issue? We are keen to update the Checklist of Taiwan. Thanks,
Chihjen

**Comment by MortenHofft** [comment]
Been running for a month now. Might make sense to add a link to the old validator while the quirks are being ironed out?

**Comment by ghost** [comment]
@MortenHofft where is the old one, please?
And, any error message produced? Perhaps we can diagnose from the data preparation process.

**Comment by MortenHofft** [comment]
I simply meant this one https://tools.gbif.org/dwca-validator/? I'm afraid I don't know anything about the validator - so I'll leave that to above mentioned  :)

**Comment by ghost** [comment]
@MortenHofft good to know it's still online. Thought it's retired with the debut of the new one. Hope the current stalled process will resolve soon. Thanks!

**Comment by cgendreau** [comment]
@cjk-halodule could you send me the file?

**Comment by MattBlissett** [comment]
https://www.gbif.org/tools/data-validator/1521462679720 is the "processing" result, and I will send the file to Christian from the cache.

**Comment by MattBlissett** [comment]
There are two fixes relevant here:
1) Reporting CSV files with empty column headers
2) Processing using disk-based storage rather than memory, important for larger checklists.

This dataset now processes successfully, although I haven't looked in detail at the result: https://www.gbif.org/tools/data-validator/1528990527569

The validator is still a bit unstable, I hope to work on that next week. Your checklist shouldn't take more than an hour to process, probably more like ½ hour, so give up waiting after that long and reopen this issue.

Cheers,
